name: my_store_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dartz: ^0.10.1
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.9.0
  google_sign_in: ^6.1.0
  shared_preferences: ^2.1.0
  firebase_core: ^2.32.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
